library(lattice)
set.seed(1)
loci <- data.frame(score=c(rbeta(800,10,10),rbeta(100,0.15,1),rbeta(100,1,0.25)),
  type=factor(c(rep("Neutral",800),rep("Positive",100),rep("Balancing",100)))) 
head(loci)
p <- densityplot(~score,loci,groups=type,auto.key=list(space="top",columns=3),n=500,main=tit <- "Distribution of scores by selection type")
pdf("confusing-legend.pdf",h=4)
print(p)
dev.off()
library(directlabels)
labeled <- direct.label(p)
pdf("direct-labeled-density.pdf",h=4)
print(labeled)
dev.off()
library(ggplot2)
theme_set(theme_grey())
pdf("ggplot2-density.pdf",h=4)
ggdensity <- qplot(score,data=loci,color=type,geom="density",main=tit)
print(direct.label(ggdensity))
dev.off()

data(BodyWeight,package="nlme")
ratplot <- xyplot(weight~Time|Diet,BodyWeight,groups=Rat,type="l",layout=c(3,1),
                  auto.key=list(space="right",points=FALSE,lines=TRUE),
                  main="Rat weight over time by treatment")
pdf("rat.pdf",h=4.5,w=7)
print(ratplot)
dev.off()
pdf("directlabel-rat.pdf",h=4.5,w=7)
print(direct.label(update(ratplot,xlim=c(0,72)),last.qp))
dev.off()
