library(lattice)
loci <- data.frame(score=c(rbeta(800,10,10),rbeta(100,0.15,1),rbeta(100,1,0.15)),
  type=factor(c(rep("Neutral",800),rep("Positive",100),rep("Balancing",100))))
p <- densityplot(~score,loci,groups=type,auto.key=list(space="top",columns=3),n=500)
pdf("confusing-legend.pdf")
print(p)
dev.off()
library(directlabels)
labeled <- direct.label(p)
pdf("direct-labeled-density.pdf")
print(labeled)
dev.off()
library(ggplot2)
pdf("ggplot2-density.pdf")
ggdensity <- qplot(score,data=loci,color=type,geom="density")
print(direct.label(ggdensity))
dev.off()
