2012-03-29-HOCKING-directlabels-semin-r.pdf: 2012-03-29-HOCKING-directlabels-semin-r.tex
	pdflatex 2012-03-29-HOCKING-directlabels-semin-r
	pdflatex 2012-03-29-HOCKING-directlabels-semin-r
2012-03-29-HOCKING-directlabels-semin-r.tex: 2012-03-29-HOCKING-directlabels-semin-r.Rnw
	echo 'library(knitr);knit("2012-03-29-HOCKING-directlabels-semin-r.Rnw")'|R --vanilla
